#!/usr/bin/env bash
# triage-cluster.sh — read-only report grouping feedback_*.md files by:
#   1. status distribution (active / anti-pattern / missing)
#   2. filename-prefix clusters with >= 2 members (first underscore token)
#   3. shared file-path mentions in body (paths repeated across >= 2 files)
#
# Output: markdown to stdout. Never mutates anything in the memory dir.

set -u
set -o pipefail

DIR="${MEMORY_DIR:?MEMORY_DIR env var required — pass the path to your Claude memory dir}"

if [ ! -d "${DIR}" ]; then
  echo "triage-cluster: memory dir not found: ${DIR}" >&2
  exit 2
fi

# Collect (file, status) tuples into a temp index.
TMP=$(mktemp -d)
trap 'rm -rf "${TMP}"' EXIT
INDEX="${TMP}/index.tsv"
: > "${INDEX}"

shopt -s nullglob
for f in "${DIR}"/feedback_*.md; do
  base=$(basename "$f")

  # Frontmatter window: between first and second `---`.
  fences=$(grep -n '^---$' "$f" | head -2 | cut -d: -f1)
  open_line=$(printf '%s\n' "$fences" | sed -n '1p')
  close_line=$(printf '%s\n' "$fences" | sed -n '2p')

  status="(missing)"
  description=""
  if [ -n "${open_line:-}" ] && [ -n "${close_line:-}" ] && [ "$open_line" = "1" ]; then
    fm=$(sed -n "$((open_line + 1)),$((close_line - 1))p" "$f")
    s=$(printf '%s\n' "$fm" | grep -E '^status:[[:space:]]' | head -1 | sed -E 's/^status:[[:space:]]*//')
    [ -n "$s" ] && status="$s"
    description=$(printf '%s\n' "$fm" | grep -E '^description:[[:space:]]' | head -1 | sed -E 's/^description:[[:space:]]*//')
  fi
  printf '%s\t%s\t%s\n' "$base" "$status" "$description" >> "${INDEX}"
done

today=$(date +%Y-%m-%d)
total=$(wc -l < "${INDEX}" | tr -d ' ')
n_active=$(awk -F'\t' '$2=="active"{c++}END{print c+0}' "${INDEX}")
n_anti=$(awk -F'\t' '$2=="anti-pattern"{c++}END{print c+0}' "${INDEX}")
n_missing=$(awk -F'\t' '$2=="(missing)"{c++}END{print c+0}' "${INDEX}")
n_other=$((total - n_active - n_anti - n_missing))

# --------------- output ---------------
cat <<EOF
# Memory Triage Report — ${today}

> Generated by \`triage-cluster.sh\`. Read-only: nothing in \`${DIR}\` was modified.
> The user (with the \`mo-memory-triage\` skill) decides which feedbacks become
> anti-pattern. This report only surfaces candidates by similarity.

## Status distribution

- total feedbacks: ${total}
- active: ${n_active}
- anti-pattern: ${n_anti}
- (missing status): ${n_missing}
EOF

if [ "$n_other" -gt 0 ]; then
  echo "- other / unrecognized: ${n_other}"
fi

if [ "$n_missing" -gt 0 ]; then
  echo
  echo "> ⚠️ ${n_missing} feedback(s) lack a \`status:\` field. Run \`bootstrap-status.sh\` before triaging."
fi

echo
echo "## Clusters by filename prefix (≥ 2 members)"
echo
# Bucket by the first underscore token after `feedback_`. e.g.
#   feedback_codex_review_multi_round.md → codex
prefix_buckets=$(awk -F'\t' '{
  name=$1
  sub(/^feedback_/, "", name)
  sub(/_.*/, "", name)
  print name "\t" $1 "\t" $2 "\t" $3
}' "${INDEX}" | sort)

# Find prefixes with >= 2 members.
multi_prefixes=$(printf '%s\n' "$prefix_buckets" | awk -F'\t' '{print $1}' | sort | uniq -c | awk '$1>=2{print $2}')

if [ -z "$multi_prefixes" ]; then
  echo "_No multi-member prefix clusters._"
else
  while IFS= read -r prefix; do
    [ -z "$prefix" ] && continue
    echo "### \`${prefix}_*\`"
    printf '%s\n' "$prefix_buckets" | awk -F'\t' -v p="$prefix" '$1==p {
      printf "- `%s` [%s] — %s\n", $2, $3, $4
    }'
    echo
  done <<< "$multi_prefixes"
fi

echo "## Clusters by shared file-path mention (≥ 2 members)"
echo
# Extract candidate file paths (>= 1 slash, ending in known extension) from
# each feedback body. Then bucket by path → list feedbacks mentioning it.
PATHS_TSV="${TMP}/paths.tsv"
: > "${PATHS_TSV}"

for f in "${DIR}"/feedback_*.md; do
  base=$(basename "$f")
  fences=$(grep -n '^---$' "$f" | head -2 | cut -d: -f1)
  close_line=$(printf '%s\n' "$fences" | sed -n '2p')
  body_start=1
  if [ -n "${close_line:-}" ]; then
    body_start=$((close_line + 1))
  fi
  # Match `dir/sub/.../file.ext` style paths (avoid matching URLs, code blocks
  # syntax, etc. by requiring path-like prefix). Common extensions only.
  sed -n "${body_start},\$p" "$f" \
    | grep -oE '[a-zA-Z][a-zA-Z0-9_-]+/[a-zA-Z0-9_./~*-]+\.(ts|tsx|jsx?|py|md|sh|css|html|json|yaml|yml)' \
    | sort -u \
    | while IFS= read -r p; do
        [ -z "$p" ] && continue
        printf '%s\t%s\n' "$p" "$base" >> "${PATHS_TSV}"
      done
done

if [ ! -s "${PATHS_TSV}" ]; then
  echo "_No file-path mentions extracted._"
else
  multi_paths=$(awk -F'\t' '{print $1}' "${PATHS_TSV}" | sort | uniq -c | awk '$1>=2{print $1, $2}' | sort -rn)
  if [ -z "$multi_paths" ]; then
    echo "_No file paths shared across ≥ 2 feedbacks._"
  else
    printf '%s\n' "$multi_paths" | while IFS= read -r line; do
      count=$(echo "$line" | awk '{print $1}')
      path=$(echo "$line" | awk '{print $2}')
      echo "### \`${path}\`  (mentioned by ${count})"
      awk -F'\t' -v p="$path" '$1==p {print $2}' "${PATHS_TSV}" | sort -u | while IFS= read -r m; do
        s=$(awk -F'\t' -v n="$m" '$1==n {print $2}' "${INDEX}")
        d=$(awk -F'\t' -v n="$m" '$1==n {print $3}' "${INDEX}")
        printf -- '- `%s` [%s] — %s\n' "$m" "$s" "$d"
      done
      echo
    done
  fi
fi

echo "## Clusters by topic tag (≥ 2 members)"
echo
# Extract `topics: [a, b, c]` from each frontmatter (inline YAML list form
# only — block form unsupported in v1). Bucket files by topic value.
TOPICS_TSV="${TMP}/topics.tsv"
: > "${TOPICS_TSV}"
for f in "${DIR}"/feedback_*.md; do
  base=$(basename "$f")
  fences=$(grep -n '^---$' "$f" | head -2 | cut -d: -f1)
  open_line=$(printf '%s\n' "$fences" | sed -n '1p')
  close_line=$(printf '%s\n' "$fences" | sed -n '2p')
  [ -z "${open_line:-}" ] || [ -z "${close_line:-}" ] && continue
  topics_line=$(sed -n "$((open_line + 1)),$((close_line - 1))p" "$f" | grep -E '^topics:[[:space:]]*\[' | head -1)
  [ -z "$topics_line" ] && continue
  # `topics: [a, b, c]` → "a, b, c"
  csv=$(printf '%s' "$topics_line" | sed -E 's/^topics:[[:space:]]*\[([^]]*)\].*/\1/' | tr -d ' ')
  [ -z "$csv" ] && continue
  IFS=',' read -ra arr <<< "$csv"
  for t in "${arr[@]}"; do
    [ -z "$t" ] && continue
    printf '%s\t%s\n' "$t" "$base" >> "${TOPICS_TSV}"
  done
done

if [ ! -s "${TOPICS_TSV}" ]; then
  echo "_No \`topics:\` tags found in any feedback frontmatter._"
else
  multi_topics=$(awk -F'\t' '{print $1}' "${TOPICS_TSV}" | sort | uniq -c | awk '$1>=2{print $1, $2}' | sort -rn)
  singletons=$(awk -F'\t' '{print $1}' "${TOPICS_TSV}" | sort | uniq -c | awk '$1==1{print $2}' | sort)
  if [ -z "$multi_topics" ]; then
    echo "_No topic tags shared across ≥ 2 feedbacks._"
  else
    printf '%s\n' "$multi_topics" | while IFS= read -r line; do
      count=$(echo "$line" | awk '{print $1}')
      topic=$(echo "$line" | awk '{print $2}')
      echo "### \`${topic}\`  (${count} members)"
      awk -F'\t' -v t="$topic" '$1==t {print $2}' "${TOPICS_TSV}" | sort -u | while IFS= read -r m; do
        s=$(awk -F'\t' -v n="$m" '$1==n {print $2}' "${INDEX}")
        d=$(awk -F'\t' -v n="$m" '$1==n {print $3}' "${INDEX}")
        printf -- '- `%s` [%s] — %s\n' "$m" "$s" "$d"
      done
      echo
    done
  fi
  if [ -n "$singletons" ]; then
    echo "_Singleton topic tags (used by only 1 feedback — possible typo or seed for a future cluster):_"
    printf '%s\n' "$singletons" | while IFS= read -r t; do
      [ -n "$t" ] && echo "- \`${t}\`"
    done
    echo
  fi
fi

echo "## Anti-patterns (current)"
echo
n_listed=0
while IFS=$'\t' read -r name status desc; do
  if [ "$status" = "anti-pattern" ]; then
    printf -- '- `%s` — %s\n' "$name" "$desc"
    n_listed=$((n_listed + 1))
  fi
done < "${INDEX}"
if [ "$n_listed" -eq 0 ]; then
  echo "_None yet. Use the skill to mark candidates._"
fi
